"use client";
import { useEffect,useState } from "react";
import { useAuth } from "@/context/AuthContext";
interface ReferralRow{id:string;referralCode:string;status:string;referredUserId?:string|null;referrerReward?:number;referredCustomerDiscount?:number}
interface UserMini{uid:string;name?:string;email?:string}
export default function ReferralsPage(){
 const {user}=useAuth(); const [referral,setReferral]=useState<ReferralRow|null>(null); const [campaign,setCampaign]=useState<any>(null); const [referred,setReferred]=useState<ReferralRow[]>([]); const [users,setUsers]=useState<Record<string,UserMini>>({}); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!user)return;void(async()=>{const token=await user.getIdToken();const [a,b]=await Promise.all([fetch("/api/referrals/ensure",{method:"POST",headers:{Authorization:`Bearer ${token}`}}),fetch("/api/referrals/mine",{headers:{Authorization:`Bearer ${token}`}})]);const ensure=await a.json();const mine=await b.json();if(!a.ok||ensure.success===false)throw new Error(ensure.message??"Unable to load referral program.");if(!b.ok||mine.success===false)throw new Error(mine.message??"Unable to load referred users.");setCampaign(ensure.active&&ensure.campaign?ensure.campaign:null);setReferral(ensure.referral??null);setReferred((mine.referrals??[]).filter((row: ReferralRow) => Boolean(row.referredUserId)));setUsers(mine.users??{});})().catch(e=>setMessage(e instanceof Error?e.message:"Unable to load referrals.")).finally(()=>setLoading(false))},[user]);
 if(loading)return <div className="rounded-2xl border bg-white p-8">Loading referral program...</div>;
 if(!campaign)return <main className="space-y-6"><h1 className="font-cinzel text-4xl">My Referrals</h1><div className="rounded-2xl border bg-white p-8 text-neutral-500">The referral program is not currently active.</div></main>;
 const code=referral?.referralCode??""; const invite=typeof window!=="undefined"?`${window.location.origin}/register?ref=${encodeURIComponent(code)}`:""; const reward=campaign.referrerReward; const customerReward=campaign.referredCustomerReward;
 return <main className="space-y-8"><section><p className="text-sm uppercase tracking-[0.3em] text-[#C9A227]">Referral Program</p><h1 className="mt-2 font-cinzel text-4xl">My Referrals</h1><p className="mt-3 text-neutral-600">Invite new customers and earn rewards after their qualifying order.</p></section><section className="rounded-3xl border bg-white p-8 shadow-sm"><h2 className="text-xl font-semibold">Your Referral Code</h2><div className="mt-5 flex flex-wrap gap-3"><code className="rounded-xl bg-neutral-100 px-5 py-3 font-bold tracking-widest">{code}</code><button onClick={()=>navigator.clipboard.writeText(code)} className="rounded-xl border px-4 py-3 text-sm font-semibold">Copy Code</button><button onClick={()=>navigator.clipboard.writeText(invite)} className="rounded-xl border px-4 py-3 text-sm font-semibold">Copy Invite Link</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-neutral-50 p-5"><p className="text-xs uppercase tracking-widest text-neutral-400">New customer benefit</p><p className="mt-2 text-2xl font-bold">{customerReward.type==="PERCENTAGE"?`${customerReward.value}% OFF`:`₹${customerReward.value} OFF`}</p>{customerReward.maximumDiscount!=null&&<p className="mt-1 text-sm text-neutral-500">Maximum ₹{Number(customerReward.maximumDiscount).toLocaleString("en-IN")}</p>}</div><div className="rounded-2xl bg-neutral-50 p-5"><p className="text-xs uppercase tracking-widest text-neutral-400">Your reward</p><p className="mt-2 text-2xl font-bold">{reward.type==="PERCENTAGE"?`${reward.value}%`:`₹${reward.value}`} reward</p><p className="mt-1 text-sm text-neutral-500">Added to your reward wallet after a qualifying order.</p></div></div></section><section className="rounded-3xl border bg-white shadow-sm"><div className="border-b p-6"><h2 className="text-xl font-semibold">Referred Users</h2><p className="mt-1 text-sm text-neutral-500">People who registered through your referral code.</p></div><div className="divide-y">{referred.length===0?<p className="p-6 text-neutral-500">No referred users yet.</p>:referred.map(row=>{const person=row.referredUserId?users[row.referredUserId]:undefined;return <div key={row.id} className="flex flex-col gap-3 p-6 md:flex-row md:items-center md:justify-between"><div><p className="font-semibold">{person?.name||"Pending registration"}</p><p className="text-sm text-neutral-500">{person?.email||row.referredUserId||"Waiting for registration"}</p></div><div className="flex items-center gap-3"><span className="rounded-full border px-3 py-1 text-xs font-semibold">{row.status}</span>{row.referrerReward?<span className="text-sm font-semibold text-[#8f7414]">₹{Number(row.referrerReward).toLocaleString("en-IN")} reward</span>:null}</div></div>})}</div></section>{message&&<p className="text-sm text-red-600">{message}</p>}</main>;
}
