export const ORDER_STATUS = {
  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_SUBMITTED: "PAYMENT_SUBMITTED",
  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",
  PAYMENT_REJECTED: "PAYMENT_REJECTED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  IN_PROGRESS: "IN_PROGRESS",
  QUALITY_CHECK: "QUALITY_CHECK",
  PACKAGING: "PACKAGING",
  SHIPPED: "SHIPPED",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
} as const;

export type OrderStatus =
  (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];