/**
 * Order Status
 * Single source of truth for the complete order lifecycle.
 */

export const ORDER_STATUS = {
  DRAFT: "DRAFT",

  PAYMENT_PENDING: "PAYMENT_PENDING",

  PAYMENT_SUBMITTED: "PAYMENT_SUBMITTED",

  PAYMENT_VERIFIED: "PAYMENT_VERIFIED",

  PAYMENT_REJECTED: "PAYMENT_REJECTED",

  ARTWORK_QUEUE: "ARTWORK_QUEUE",

  DRAWING: "DRAWING",

  QUALITY_CHECK: "QUALITY_CHECK",

  COMPLETED: "COMPLETED",

  PACKAGED: "PACKAGED",

  SHIPPED: "SHIPPED",

  DELIVERED: "DELIVERED",

  CANCELLED: "CANCELLED",
} as const;

export type OrderStatus =
  (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS];

export const ACTIVE_ORDER_STATUSES: OrderStatus[] = [
  ORDER_STATUS.PAYMENT_PENDING,
  ORDER_STATUS.PAYMENT_SUBMITTED,
  ORDER_STATUS.PAYMENT_VERIFIED,
  ORDER_STATUS.ARTWORK_QUEUE,
  ORDER_STATUS.DRAWING,
  ORDER_STATUS.QUALITY_CHECK,
];

export const FINISHED_ORDER_STATUSES: OrderStatus[] = [
  ORDER_STATUS.COMPLETED,
  ORDER_STATUS.PACKAGED,
  ORDER_STATUS.SHIPPED,
  ORDER_STATUS.DELIVERED,
];

export const FAILED_ORDER_STATUSES: OrderStatus[] = [
  ORDER_STATUS.PAYMENT_REJECTED,
  ORDER_STATUS.CANCELLED,
];