"use client";
import Link from "next/link";
import { ArrowRight, Calendar, CreditCard, Palette } from "lucide-react";
import { useState } from "react";
import { useAuth } from "@/context/AuthContext";
import { toast } from "sonner";
import type { Order } from "@/types/order";

interface OrderCardProps { order: Order; }
const paymentStatusColor: Record<string,string>={PENDING:"bg-yellow-100 text-yellow-800",SUBMITTED:"bg-blue-100 text-blue-800",VERIFIED:"bg-green-100 text-green-800",REJECTED:"bg-red-100 text-red-800"};
const orderStatusColor: Record<string,string>={PAYMENT_PENDING:"bg-yellow-100 text-yellow-800",PAYMENT_SUBMITTED:"bg-blue-100 text-blue-800",PAYMENT_VERIFIED:"bg-green-100 text-green-800",ARTWORK_QUEUE:"bg-purple-100 text-purple-800",DRAWING:"bg-indigo-100 text-indigo-800",QUALITY_CHECK:"bg-orange-100 text-orange-800",COMPLETED:"bg-emerald-100 text-emerald-800",PACKAGED:"bg-cyan-100 text-cyan-800",SHIPPED:"bg-sky-100 text-sky-800",DELIVERED:"bg-green-100 text-green-800",CANCELLED:"bg-red-100 text-red-800"};
const cancellable=["PAYMENT_PENDING","PAYMENT_SUBMITTED","PAYMENT_VERIFIED","ARTWORK_QUEUE"];
export function OrderCard({order}:OrderCardProps){
 const {user}=useAuth(); const [cancelling,setCancelling]=useState(false); const paymentStatus=order.payment.status; const orderStatus=order.status;
 const cancel=async()=>{if(!user||cancelling)return;const confirmed=window.confirm("Cancel this order? Payment is non-refundable. If your payment was verified, the paid amount will be credited to your reward wallet for your next order or transfer to another eligible person.");if(!confirmed)return;setCancelling(true);try{const token=await user.getIdToken();const response=await fetch("/api/orders/cancel",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({orderId:order.id})});const data=await response.json();if(!response.ok)throw new Error(data.message??"Unable to cancel order.");toast.success(data.message??"Order cancelled.");window.location.reload();}catch(e){toast.error(e instanceof Error?e.message:"Unable to cancel order.");}finally{setCancelling(false)}};
 return <div className="rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm transition hover:shadow-md"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-zinc-500">{order.orderNumber}</p><h2 className="mt-1 text-xl font-semibold">{order.portrait.packageName}</h2></div><span className={`whitespace-nowrap rounded-full px-3 py-1 text-xs font-semibold ${orderStatusColor[orderStatus]??"bg-zinc-100 text-zinc-700"}`}>{orderStatus.replaceAll("_"," ")}</span></div><div className="mt-6 space-y-3"><div className="flex items-center gap-2 text-sm text-zinc-700"><Palette size={18}/><span>{order.portrait.size} • {order.portrait.subjects} Subject(s)</span></div><div className="flex items-center gap-2 text-sm text-zinc-700"><CreditCard size={18}/><span className={`rounded-full px-2 py-1 text-xs font-medium ${paymentStatusColor[paymentStatus]??"bg-zinc-100 text-zinc-700"}`}>{paymentStatus}</span></div><div className="flex items-center gap-2 text-sm text-zinc-700"><Calendar size={18}/><span>{new Date(order.createdAt as unknown as Date).toLocaleDateString("en-IN")}</span></div></div><div className="mt-8 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm text-zinc-500">Amount</p><p className="text-2xl font-bold">₹{order.payment.amount.toLocaleString("en-IN")}</p></div><div className="flex flex-wrap gap-3"><Link href={`/orders/${order.id}`} className="inline-flex items-center gap-2 rounded-xl border border-zinc-300 px-5 py-3 text-sm font-medium text-zinc-900 transition hover:bg-zinc-100">View Order<ArrowRight size={18}/></Link>{cancellable.includes(orderStatus)&&<button type="button" onClick={()=>void cancel()} disabled={cancelling} className="inline-flex items-center gap-2 rounded-xl border border-red-200 px-5 py-3 text-sm font-medium text-red-600 transition hover:bg-red-50 disabled:opacity-50">{cancelling?"Cancelling...":"Cancel Order"}</button>}{(paymentStatus==="PENDING"||paymentStatus==="REJECTED")&&<Link href={`/payment/${order.id}`} className="inline-flex items-center gap-2 rounded-xl bg-black px-5 py-3 text-sm font-medium text-white transition hover:bg-zinc-800">{paymentStatus==="REJECTED"?"Resubmit Payment":"Continue Payment"}<CreditCard size={18}/></Link>}</div></div></div>;
}
