"use client";
import { useState } from "react";
import { Gift, Send, Star } from "lucide-react";
import { useAuth } from "@/context/AuthContext";
import { useUserProfile } from "@/hooks/useUserProfile";
import { toast } from "sonner";

export default function ArtistRewardsPage(){
 const {user}=useAuth(); const {profile}=useUserProfile(); const coins=Math.max(0,Number(profile?.referralRewardCoins??0)); const [recipient,setRecipient]=useState(""); const [amount,setAmount]=useState(0); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 const transfer=async()=>{if(!user||!recipient.trim()||amount<=0){setMessage("Enter a customer email and a valid coin amount.");return;}if(amount>coins){setMessage(`You only have ${coins} coin(s) available.`);return;}setLoading(true);setMessage("");try{const token=await user.getIdToken();const response=await fetch("/api/rewards/transfer",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({recipient,amount,type:"ARTIST2C"})});const data=await response.json();if(!response.ok)throw new Error(data.message??"Transfer failed.");toast.success(`${amount} reward coin(s) transferred to the customer.`);setRecipient("");setAmount(0);window.location.reload();}catch(e){const text=e instanceof Error?e.message:"Transfer failed.";setMessage(text);toast.error(text);}finally{setLoading(false)}};
 return <main className="space-y-8"><section><p className="text-sm uppercase tracking-[0.3em] text-[#C9A227]">Artist Rewards</p><h1 className="mt-2 font-cinzel text-4xl">Reward Wallet</h1><p className="mt-3 text-neutral-600">Your reward wallet is the single available reward balance. Artist rewards can be transferred only to a customer account.</p></section><section className="grid gap-6 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-8 shadow-sm"><Star className="text-[#C9A227]"/><p className="mt-4 text-sm text-neutral-500">Available Wallet</p><p className="mt-1 text-5xl font-bold text-[#8f7414]">{coins} coins</p><p className="mt-2 text-sm text-neutral-500">Value: ₹{coins.toLocaleString("en-IN")}</p></div><div className="rounded-3xl bg-black p-8 text-white"><Gift className="text-[#C9A227]"/><h2 className="mt-4 text-xl font-semibold">Artist → Customer Transfer</h2><p className="mt-2 text-sm text-white/60">No customer-to-customer option is shown for artists.</p><div className="mt-5 space-y-3"><input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Customer email" className="w-full rounded-xl bg-white px-4 py-3 text-black"/><input type="number" min="1" max={coins} value={amount||""} onChange={e=>setAmount(Math.max(0,Math.floor(Number(e.target.value)||0)))} placeholder="Coins" className="w-full rounded-xl bg-white px-4 py-3 text-black"/><button type="button" disabled={loading||coins<=0} onClick={()=>void transfer()} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[#C9A227] px-4 py-3 font-semibold text-black disabled:opacity-50"><Send size={16}/>{loading?"Transferring...":"Transfer to Customer"}</button>{message&&<p className="text-sm text-red-200">{message}</p>}</div></div></section></main>;
}
