//10/07/26
import type { Metadata } from "next";
import { Cinzel, Montserrat, Poppins } from "next/font/google";
import "./globals.css";
import { AppShell } from "@/components/layout/AppShell";
import { AuthProvider } from "@/context/AuthContext";
import { Toaster } from "sonner";

const cinzel = Cinzel({
  subsets: ["latin"],
  variable: "--font-heading",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-body",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-accent",
});

export const metadata: Metadata = {
  title: "Artistic Soham Shinde",
  description: "Turning Memories into Timeless Art.",
  keywords: [
    "Pencil Portrait",
    "Custom Portrait",
    "Handmade Art",
    "Sketch Artist",
    "Artistic Soham Shinde",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${montserrat.variable} ${poppins.variable}`}
      >
        <AuthProvider>
          <AppShell>
            {children}
          </AppShell>

          <Toaster
            richColors
            position="top-right"
          />
        </AuthProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
