"use client";
import { useEffect,useMemo,useState } from "react";
import { Users,UserRound,ShoppingBag,BadgeIndianRupee,Clock3,CheckCircle2,TicketPercent,Gift,FileText } from "lucide-react";
import Link from "next/link";
import { getAllUsers } from "@/services/user";
import { OrderService } from "@/services/order";
import { getOffers } from "@/services/offers";
import { getReferralCampaigns } from "@/services/referrals";
import type { Order } from "@/types/order";
import { ORDER_STATUS } from "@/constants/order-status";
import type { OfferDocument } from "@/types/offer";
import type { ReferralCampaignDocument } from "@/types/referral";
import { ADMIN_NAVIGATION } from "@/constants/adminNavigation";

export default function AdminPage(){
 const [users,setUsers]=useState<any[]>([]); const [orders,setOrders]=useState<Order[]>([]); const [offers,setOffers]=useState<OfferDocument[]>([]); const [campaigns,setCampaigns]=useState<ReferralCampaignDocument[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
 useEffect(()=>{Promise.all([getAllUsers(),OrderService.getAll(),getOffers(),getReferralCampaigns()]).then(([u,o,of,c])=>{setUsers(u);setOrders(o);setOffers(of);setCampaigns(c)}).catch(()=>setError("Unable to load dashboard statistics.")).finally(()=>setLoading(false));},[]);
 const stats=useMemo(()=>{const customers=users.filter(u=>u.role==="CUSTOMER").length;const artists=users.filter(u=>u.role==="ARTIST").length;const pendingPayments=orders.filter(o=>o.status===ORDER_STATUS.PAYMENT_PENDING||o.status===ORDER_STATUS.PAYMENT_SUBMITTED).length;const completed=orders.filter(o=>[ORDER_STATUS.COMPLETED,ORDER_STATUS.PACKAGED,ORDER_STATUS.SHIPPED,ORDER_STATUS.DELIVERED].includes(o.status as any)).length;const cancelled=orders.filter(o=>o.status===ORDER_STATUS.CANCELLED).length;const active=orders.length-completed-cancelled;const verifiedOrders=orders.filter(o=>o.payment?.status==="VERIFIED");const revenue=verifiedOrders.reduce((sum,o)=>sum+Number(o.payment?.amount??0),0);const avg=verifiedOrders.length?revenue/verifiedOrders.length:0;return{customers,artists,pendingPayments,completed,cancelled,active,revenue,avg,verifiedOrders:verifiedOrders.length};},[users,orders]);
 return <main className="space-y-8"><section><p className="text-sm uppercase tracking-[0.3em] text-[#C9A227]">Administration</p><h1 className="mt-2 font-cinzel text-4xl font-bold">Business Dashboard</h1><p className="mt-3 max-w-3xl text-neutral-600">A live operational overview of customers, artists, orders, revenue, promotions and referrals.</p></section>{error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 <section className="grid gap-5 sm:grid-cols-2 xl:grid-cols-4"><Stat title="Customers" value={loading?"—":stats.customers} icon={<Users size={22}/>}/><Stat title="Artists" value={loading?"—":stats.artists} icon={<UserRound size={22}/>}/><Stat title="Orders" value={loading?"—":orders.length} icon={<ShoppingBag size={22}/>}/><Stat title="Verified Revenue" value={loading?"—":`₹${stats.revenue.toLocaleString("en-IN")}`} icon={<BadgeIndianRupee size={22}/>}/></section>

 <section className="grid gap-6 lg:grid-cols-3"><div className="rounded-3xl border bg-white p-7 shadow-sm lg:col-span-2"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Business Utilisation</h2><p className="mt-1 text-sm text-neutral-500">Current workload and promotion readiness.</p></div><CheckCircle2 className="text-[#C9A227]"/></div><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Mini label="Active Orders" value={loading?"—":stats.active}/><Mini label="Pending Payments" value={loading?"—":stats.pendingPayments}/><Mini label="Completed" value={loading?"—":stats.completed}/><Mini label="Cancelled" value={loading?"—":stats.cancelled}/><Mini label="Average Verified Order" value={loading?"—":`₹${Math.round(stats.avg).toLocaleString("en-IN")}`}/></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><Mini label="Active Offers" value={offers.filter(o=>o.enabled).length}/><Mini label="Offers in Testing" value={offers.filter(o=>!o.enabled).length}/><Mini label="Referral Campaigns" value={campaigns.length}/><Mini label="Active Referral Campaigns" value={campaigns.filter(c=>c.enabled).length}/></div></div><div className="rounded-3xl border bg-black p-7 text-white shadow-sm"><p className="text-xs uppercase tracking-[0.25em] text-[#C9A227]">Quick access</p><h2 className="mt-2 text-2xl font-semibold">Manage business</h2><div className="mt-6 grid gap-3">{ADMIN_NAVIGATION.filter(({href})=>!['/admin','/admin/settings','/admin/profile','/'].includes(href)).slice(0,10).map(({label,href})=><Link key={href} href={href} className="rounded-xl border border-white/15 px-4 py-3 text-sm hover:bg-white/10">{label}</Link>)}</div></div></section>
 <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-4"><Link href="/admin/invoices" className="rounded-2xl border bg-white p-6 shadow-sm"><FileText className="text-[#C9A227]"/><h3 className="mt-4 font-semibold">Invoice Management</h3><p className="mt-1 text-sm text-neutral-500">Print A5 invoices or A4 two-up copies.</p></Link><Link href="/admin/coupons" className="rounded-2xl border bg-white p-6 shadow-sm"><TicketPercent className="text-[#C9A227]"/><h3 className="mt-4 font-semibold">Coupons & Offers</h3><p className="mt-1 text-sm text-neutral-500">Keep new offers in testing until published.</p></Link><Link href="/admin/referrals" className="rounded-2xl border bg-white p-6 shadow-sm"><Gift className="text-[#C9A227]"/><h3 className="mt-4 font-semibold">Referral Program</h3><p className="mt-1 text-sm text-neutral-500">Configure campaigns and customer rewards.</p></Link><Link href={orders[0]?`/invoices/${orders[0].id}`:"/admin/orders"} className="rounded-2xl border bg-white p-6 shadow-sm"><Clock3 className="text-[#C9A227]"/><h3 className="mt-4 font-semibold">Latest Order</h3><p className="mt-1 text-sm text-neutral-500">{orders[0]?.orderNumber??"No orders yet"}</p></Link></section>
 </main>;
}
function Stat({title,value,icon}:{title:string;value:string|number;icon:React.ReactNode}){return <div className="rounded-3xl border bg-white p-6 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-sm text-neutral-500">{title}</p><p className="mt-3 text-3xl font-bold">{value}</p></div><div className="rounded-xl bg-[#C9A227]/10 p-3 text-[#C9A227]">{icon}</div></div></div>}
function Mini({label,value}:{label:string;value:string|number}){return <div className="rounded-2xl bg-neutral-50 p-5"><p className="text-sm text-neutral-500">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
