"use client";
import { useEffect,useState } from "react";
import { artistInfo, websiteDeveloper } from "@/data/about";
import { getSiteContent, saveSiteContent } from "@/services/site-content.service";

export default function AdminAboutPage(){
 const [data,setData]=useState({name:artistInfo.name,title:artistInfo.title,location:artistInfo.location,description:artistInfo.description.join("\n\n"),signature:artistInfo.signature});
 const [developer,setDeveloper]=useState({title:websiteDeveloper.title,developer:websiteDeveloper.developer,description:websiteDeveloper.description.join("\n\n"),github:websiteDeveloper.github,linkedin:websiteDeveloper.linkedin,instagram:websiteDeveloper.instagram,whatsapp:websiteDeveloper.whatsapp});
 const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");
 useEffect(()=>{Promise.all([getSiteContent("about",data),getSiteContent("aboutWebsite",developer)]).then(([a,d])=>{setData({...data,...a,description:Array.isArray(a.description)?a.description.join("\n\n"):String(a.description??data.description)});setDeveloper({...developer,...d,description:Array.isArray(d.description)?d.description.join("\n\n"):String(d.description??developer.description)})}).catch(()=>undefined)},[]);
 async function save(){setSaving(true);setMessage("");try{await Promise.all([saveSiteContent("about",data),saveSiteContent("aboutWebsite",developer)]);setMessage("About and Website Design & Development content saved.")}catch(e){setMessage(e instanceof Error?e.message:"Unable to save.")}finally{setSaving(false)}}
 return <main className="mx-auto max-w-5xl space-y-8"><section><p className="text-sm uppercase tracking-[0.3em] text-[#C9A227]">Administration</p><h1 className="mt-2 font-cinzel text-4xl">About Content</h1><p className="mt-3 text-neutral-600">Edit public About and Website Design & Development content without changing source code.</p></section><section className="rounded-3xl border bg-white p-7 shadow-sm space-y-5"><h2 className="text-xl font-semibold">Artist Content</h2>{(["name","title","location","signature"] as const).map(k=><label key={k} className="block"><span className="mb-2 block text-sm font-medium capitalize">{k}</span><input value={data[k]} onChange={e=>setData(d=>({...d,[k]:e.target.value}))} className="w-full rounded-xl border p-3"/></label>)}<label className="block"><span className="mb-2 block text-sm font-medium">Description paragraphs</span><textarea rows={12} value={data.description} onChange={e=>setData(d=>({...d,description:e.target.value}))} className="w-full rounded-xl border p-3"/></label></section><section className="rounded-3xl border bg-white p-7 shadow-sm space-y-5"><h2 className="text-xl font-semibold">Website Design & Development</h2>{(["title","developer","github","linkedin","instagram","whatsapp"] as const).map(k=><label key={k} className="block"><span className="mb-2 block text-sm font-medium capitalize">{k}</span><input value={developer[k]} onChange={e=>setDeveloper(d=>({...d,[k]:e.target.value}))} className="w-full rounded-xl border p-3"/></label>)}<label className="block"><span className="mb-2 block text-sm font-medium">Description paragraphs</span><textarea rows={10} value={developer.description} onChange={e=>setDeveloper(d=>({...d,description:e.target.value}))} className="w-full rounded-xl border p-3"/></label></section><button onClick={()=>void save()} disabled={saving} className="rounded-xl bg-[#C9A227] px-6 py-3 font-semibold text-black">{saving?"Saving...":"Save All About Content"}</button>{message&&<p className="text-sm text-neutral-600">{message}</p>}</main>
}
